version: "3"  # optional since v1.27.0
services:

  nginx:
    container_name: nginx
    image: nginx
    networks:
      - backend
    ports:
      - "80:80"
      - "8888:8888"
      - "443:443"
    volumes:
      - ./assetlinks.json:/assetlinks.json
      - ./www:/var/www
      - ./logs/nginx:/var/log/nginx
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certs:/etc/ssl
      - ./json-deeplink.json:/deeplink/json-file.json
    depends_on:
      - web

  node-docker:
    image: selenium/node-docker:4.5.0-20221004
    volumes:
      - ./assets:/opt/selenium/assets
      - ./config.toml:/opt/bin/config.toml
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - backend

  selenium-hub:
    image: selenium/hub:4.5.0-20221004
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    networks:
      - backend

  adm:
    image: "docker.pkg.github.com/daniil-lab/wp-front/wp-front:main"
    ports:
      - "3000:3000"
    networks:
      - backend

  lk:
    image: "docker.pkg.github.com/kyzinatra/wp-lk/wp-lk:main"
    ports:
      - "3001:3001"
    networks:
      - backend

  web:
    image: "docker.pkg.github.com/daniil-lab/wp-system/wp-system:main"
    ports:
      - "8080:8080"
    expose:
      - "8080"
    networks:
      - backend
    volumes:
      - ~/images:/images
      - ./chromedriver:/chromedriver
    environment:
      - SELENIUM_URL=http://selenium-hub:4444/wd/hub
      - SIGMA_USER=2025sel@gmail.com
      - SIGMA_PASS=j4nLYx
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/wp
      - SENDPULSE_CLIENT_ID=d9bdd184a2a4a14b830a8b264ce33f31
      - SENDPULSE_CLIENT_SECRET=e6a25e4d987db74d7e63543d9ca429c1
    depends_on:
      - database
      - selenium-hub

  database:
    image: "postgres"
    networks:
      - backend
    env_file:
      - database.env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

networks:
  backend:
    driver: bridge
